"""rating

Revision ID: 7317b4aedb9b
Revises: 105cdb13a760
Create Date: 2019-03-07 13:54:31.946126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7317b4aedb9b'
down_revision = '105cdb13a760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'order_rating')
    # ### end Alembic commands ###
